defaults:
  - _self_
  - encoder: encoder
  - datasets: default
  - augmentations: default
  - transforms: default
  - loss: triplet
  - optimizer: sgd

batch_size: 32
epochs: 100
validation_interval: 5
validations_without_improvement: 3
best_model_path: "best.ckpt"