defaults:
  - _self_
  - encoder: encoder
  - datasets: default
  - augmentations: default
  - transforms: default
  - loss: triplet
  - optimizer: adamw

batch_size: 32
epochs: 100
epochs_without_improvement: 10
best_model_path: "best.ckpt"