defaults:
  - _self_
  - encoder: encoder
  - datasets: default
  - augmentations: default
  - transforms: default
  - loss: triplet
  - optimizer: adamw

batch_size: 32
epochs: 100
validation_interval: 2
validations_without_improvement: 3
epoch_swap_to_hard: 3
best_model_path: "best.ckpt"
min_samples_per_id: 8